nav:
    - Project:
      - Kitchen Worlds: index.md
      - Challenges of TAMP: project-challenges.md
      # - Minutes & Notes: project-minutes.md
      # - Plans & Priorities: project-plans.md
    - Planning Domains:
      - Rearrangement Domain: domain-rearrangement.md
      - I) Predicates: domain-predicates.md
      - II) Operators: domain-operators.md
      - III) Axioms: domain-axioms.md
    - Planning Approach:
      - Baseline Planners: planner-baselines.md
      # - Approach - HPN: planner-pddlstream.md
    - Experiments:
      - Planning Problems: exp-problems.md
    - Set it up:
      - Set up the Repository: setup-repository.md
      - Set up MkDocs: setup-mkdocs.md
      - Editor's Notes: setup-notes.md
    - Tutorials:
      - LISDF: tut-lisdf.md
      - LISPDDL: tut-lispddl.md
      - PDDLStream: tut-pddlstream.md

site_name: Dev Notes
theme: readthedocs
# theme:
#     name: null
#     custom_dir: '/miniconda3/lib/python3.7/site-packages/mkdocs/themes/readthediary/'

site_favicon: css/favicon.ico
extra_css: [css/extra.css]
markdown_extensions:
    - toc:
        permalink: "#"
